[2024-08-13T19:12:05.349+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-13T19:11:52.205207+00:00 [queued]>
[2024-08-13T19:12:05.360+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-13T19:11:52.205207+00:00 [queued]>
[2024-08-13T19:12:05.361+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-08-13T19:12:05.379+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-08-13 19:11:52.205207+00:00
[2024-08-13T19:12:05.387+0000] {standard_task_runner.py:57} INFO - Started process 92 to run task
[2024-08-13T19:12:05.391+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-08-13T19:11:52.205207+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpzkqngqy5']
[2024-08-13T19:12:05.403+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask s3_upload
[2024-08-13T19:12:05.454+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-13T19:11:52.205207+00:00 [running]> on host fdf0cefe5923
[2024-08-13T19:12:05.535+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Seif Yasser' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T19:11:52.205207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-13T19:11:52.205207+00:00'
[2024-08-13T19:12:05.550+0000] {logging_mixin.py:151} INFO - __init__() got an unexpected keyword argument 'SECRET'
[2024-08-13T19:12:05.551+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/'[-1]))
  File "/opt/airflow/etls/aws_etl.py", line 29, in upload_to_s3
    s3.put(file_path, bucket + '/raw/' + s3_file_name)
TypeError: can only concatenate str (not "list") to str
[2024-08-13T19:12:05.567+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20240813T191152, start_date=20240813T191205, end_date=20240813T191205
[2024-08-13T19:12:05.580+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task s3_upload (can only concatenate str (not "list") to str; 92)
[2024-08-13T19:12:05.603+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-13T19:12:05.620+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
